import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import Curve, CurveLoop, DirectShape, ElementId, Line, XYZ
from Autodesk.Revit.DB import SolidOptions, GeometryCreationUtilities
from Autodesk.Revit.DB import BuiltInCategory as Bic
from System.Collections.Generic import List
#from rpw import db, ui, doc, uidoc

uidoc = __revit__.ActiveUIDocument
doc = uidoc.Document
"""
selection = [doc.GetElement(elem_id) for elem_id in uidoc.Selection.GetElementIds()]
first_selected = selection[0]
solid_opt = SolidOptions(ElementId.InvalidElementId, ElementId.InvalidElementId)

bbox = first_selected.get_BoundingBox(None)
bottom_z_offset = 0.1
bbox.Min = XYZ(bbox.Min.X, bbox.Min.Y, bbox.Min.Z - bottom_z_offset)
b1 = XYZ(bbox.Min.X, bbox.Min.Y, bbox.Min.Z)
b2 = XYZ(bbox.Max.X, bbox.Min.Y, bbox.Min.Z)
b3 = XYZ(bbox.Max.X, bbox.Max.Y, bbox.Min.Z)
b4 = XYZ(bbox.Min.X, bbox.Max.Y, bbox.Min.Z)
bbox_height = bbox.Max.Z - bbox.Min.Z

lines = List[Curve]()
lines.Add(Line.CreateBound(b1, b2))
lines.Add(Line.CreateBound(b2, b3))
lines.Add(Line.CreateBound(b3, b4))
lines.Add(Line.CreateBound(b4, b1))
rectangle = [CurveLoop.Create(lines)]

extrusion = GeometryCreationUtilities.CreateExtrusionGeometry(List[CurveLoop](rectangle),
                                                              XYZ.BasisZ,
                                                              bbox_height,
                                                              solid_opt)
"""                                                            
el = doc.GetElement(ElementId(1046245))   
g1 =  el.Geometry[Options()]


s1 = list(g1)

g3 = BooleanOperationsUtils.ExecuteBooleanOperation(s1, s2, BooleanOperationsType.Intersect)

category_id = ElementId(Bic.OST_GenericModel)
print(1)
tr = Transaction(doc, "solid_bbox_direct_shape")
tr.Start()
print(2)

direct_shape = DirectShape.CreateElement(doc, category_id)
direct_shape.SetShape([g for g in g1])
print(3)
direct_shape = DirectShape.CreateElement(doc, category_id)
direct_shape.SetShape([g for g in g2])

direct_shape = DirectShape.CreateElement(doc, category_id)
direct_shape.SetShape([g3])
    
tr.Commit()