import Autodesk.Revit.UI as UI
i_count = 0
letters = "АБВГДЕЖИКЛМНПРСТУФХЦЭЮЯ"
num = 1
numeric = True
suffix = "/2"
trans = Transaction(doc)

while True :
	i_count += 1
	if i_count > 100 : break
	
	try :
		e_ref = uidoc.Selection.PickObject(UI.Selection.ObjectType.Element)
		e = doc.GetElement(e_ref)

			
		trans.Start("Нумерация осей")
		if numeric :
			e.Name = "{}{}".format(num, suffix)
		else :
			e.Name = "{}{}".format(letters[num-1], suffix)
			
		trans.Commit()
		
		try : 
			num +=1 
		except :
			print("Ошибка")
			
			num = chr(ord(num)+1)
	except Exception as ex:
		print("Ошибка")
		print(ex)
		trans.RollBack()
		
		break
