
#  coding: utf-8 


from Autodesk.Revit import *
from Autodesk.Revit.DB import *
import Autodesk.Revit.Exceptions
import System 
import clr

import math, sys
import clr

import re

clr.AddReferenceToFileAndPath(r"C:\Users\Дмитрий\NetTopologySuite.2.4.0\lib\netstandard2.0\NetTopologySuite.dll")
import NetTopologySuite as nts
import NetTopologySuite.Geometries as nts_geom


lib_path = r"D:\18_проектирование\98_PythonShell"
if not lib_path in sys.path :
	sys.path.append(lib_path)
	

lib_path = r"D:\18_проектирование\98_PythonShell\Создание фильтров"
if not lib_path in sys.path :
	sys.path.append(lib_path)
	



pi2 = math.pi * 2

dut = 0.0032808398950131233

	
bic = BuiltInCategory
bip = DB.Structure.StructuralType
nonstr = bip.NonStructural
OT = UI.Selection.ObjectType


uidoc = __revit__.ActiveUIDocument
doc = uidoc.Document

	
import dm_connect_2 as dm
import dm_nearest_geometry as dm1

reload(dm)	

fc = FilteredElementCollector(doc).OfClass(ViewSchedule).ToElements()
cab1 = None
cab2 = None
for t in fc :
	#print(t.Name)
	if t.Name == "В_СС_КТ_Электрические цепи_Справочник кабеля" :
		break

		
print(t.Name)

cables = FilteredElementCollector(doc, t.Id).ToElements()
lan_cable  = None

for c in cables :
	if c.Name == "Hyperline UUTP4-C5E-S24-IN-PVC-GY-305" :
		cab1 = c
	if c.Name == "ВВГнг(А)-FRLSLTx 3x1,5" :
		cab2 = c
		
		
print(c)
tr = Transaction(doc)
tr.Start("смена кабеля")

circuits = FilteredElementCollector(doc).OfClass(Electrical.ElectricalSystem).ToElements()

for circuit in circuits :
	print(circuit.LookupParameter("Имя нагрузки").AsString())
	
	if circuit.SystemType == Electrical.ElectricalSystemType.Data :
		print("Устанавливаем витую пару")
		circuit.LookupParameter("Выбор проводника").Set(cab1.Id)
	if circuit.SystemType == Electrical.ElectricalSystemType.PowerCircuit :
		print("Устанавливаем силовой кабель")
		circuit.LookupParameter("Выбор проводника").Set(cab2.Id)
		
	circuit.LookupParameter("Запас проводника_Электрические цепи").Set(30)
	circuit.LookupParameter("Запас на разделку проводника_Электрические цепи").Set(10000*dut)
	
		
tr.Commit()
	















	


	
