# Стандарный код для импортов
import clr
from Autodesk.Revit import DB, UI
import System, sys
from imp import reload
import time
import json
dut = 0.0032808398950131233
bic = BuiltInCategory

refLocations = []
for assembly in clr.References :
	refLocations.append(assembly.Location)

libFolder = r"D:\18_проектирование\98_PythonShell"
if libFolder not in sys.path :
	sys.path.append(libFolder)
	
	
libFolder2 = r"D:\18_проектирование\pyRevitExtension\DMuzer.extension\lib"
if libFolder2 not in sys.path :
	sys.path.append(libFolder2)
	
try :
	reload(dm)
	print("Перезагрузка dmRevitClasses ok")
except Exception as ex :
	print(ex)
	import dmRevitClasses as dm
	print("импорт dmRevitClasses ok")
	
e = dm.firstSelected()
print(e)

if e.IsPipe :
	z0 = e.Location.Curve.GetEndPoint(0).Z
	z1 = e.Location.Curve.GetEndPoint(0).Z
	zm = (z0 + z1) / 2
	

av = uidoc.ActiveView


viewRange 			= av.GetViewRange()
bottomClipPlane 	= doc.GetElement(viewRange.GetLevelId(PlanViewPlane.BottomClipPlane))
topClipPlane 		= doc.GetElement(viewRange.GetLevelId(PlanViewPlane.TopClipPlane))
cutClipPlane 		= doc.GetElement(viewRange.GetLevelId(PlanViewPlane.CutPlane))
viewdepthPlane 		= doc.GetElement(viewRange.GetLevelId(PlanViewPlane.ViewDepthPlane))


bottomOffset 		= zm - bottomClipPlane.Elevation - e.diameter * 0.75
topOffset  			= zm - topClipPlane.Elevation + e.diameter * 0.75
cutOffset 			= zm - cutClipPlane.Elevation 
viewdepthOffset		= zm - viewdepthPlane.Elevation - e.diameter * 0.75


viewRange.SetOffset(PlanViewPlane.BottomClipPlane, bottomOffset)
viewRange.SetOffset(PlanViewPlane.TopClipPlane, topOffset)
viewRange.SetOffset(PlanViewPlane.CutPlane, cutOffset)
viewRange.SetOffset(PlanViewPlane.ViewDepthPlane, viewdepthOffset)

viewDm = dm.dmElement(av)
newName = av.Name + " отм. {:+0.3f} д = {:0.0f}".format(cutOffset/dut/1000, e.diameter/dut)
print(newName)
nameNum = 0
newName0 = newName
with dm.trans(a="Создание вида {}".format(newName)) :
	av2 = viewDm.copy()
	#av.EnableTemporaryViewPropertiesMode(av.Id)
	while True :
		try :
			av2.e.Name = newName0
			break
		except :
			newName0 = newName + " {}".format(nameNum)
			nameNum += 1
			if nameNum > 20 : break
			
			
		
	av2.e.SetViewRange(viewRange)
	
uidoc.ActiveView = av2.e
	
	
	