# Стандарный код для импортов
import clr
from Autodesk.Revit import DB, UI
import System, sys
from imp import reload
import time
import json
dut = 0.0032808398950131233
bic = BuiltInCategory

refLocations = []
for assembly in clr.References :
	refLocations.append(assembly.Location)

libFolder = r"D:\18_проектирование\98_PythonShell"
if libFolder not in sys.path :
	sys.path.append(libFolder)
	
	
libFolder2 = r"D:\18_проектирование\pyRevitExtension\DMuzer.extension\lib"
if libFolder2 not in sys.path :
	sys.path.append(libFolder2)
	
try :
	reload(dm)
	print("Перезагрузка dmRevitClasses ok")
except Exception as ex :
	print(ex)
	import dmRevitClasses as dm
	print("импорт dmRevitClasses ok")
	
try :
	reload(dmDoc)
	print("Перезагрузка dmRevitDoc ok")
except Exception as ex :
	print(ex)
	import dmRevitDoc as dmDoc
	print("импорт dmRevitDoc ok")
try :
	reload(dmRunningForm)
	print("Перезагрузка dmRunnigForm ok")
except Exception as ex :
	print(ex)
	import dmRunningForm 
	print("импорт dmRunnigForm ok")

try : del(form) 
except: pass 
try :
	lastCreated
except :
	lastCreated = None
import math
def callback() :
	global lastCreated

	active_view = doc.ActiveView
	bounding_box = active_view.CropBox
	center_x = (bounding_box.Min.X + bounding_box.Max.X) / 2
	center_y = (bounding_box.Min.Y + bounding_box.Max.Y) / 2
	center = XYZ(center_x, center_y, 0)
	
	scale = active_view.Scale
	radius = form.numericUpDown.Value * (20.0 / 304.8) * scale
	
	plane = Plane.CreateByNormalAndOrigin(XYZ.BasisZ, center)
	arcArray = Arc.Create(plane, radius, 0, 2 * math.pi)
	
	t = Transaction(doc, 'Добавление круга на активный вид')
	t.Start()
	
	if lastCreated is not None : doc.Delete(lastCreated.Id)
	
	lastCreated = doc.Create.NewDetailCurve(active_view, arcArray)
	
	t.Commit()

dmRunningForm.executeEvent = callback

form = dmRunningForm.LengthInputForm(sv=5)

form.Show()

pass
	
	
	
