"""
Установка рабочего набора для магистральных трубопроводов
"""
import Autodesk.Revit.UI as UI
import sys
from collections import deque
import math
from imp import reload
libpath = r"D:\18_проектирование\pyRevitExtension\DMuzer.extension\lib"
if libpath not in sys.path :
	sys.path.append(libpath)
dut = 0.0032808398950131233	
try :
	reload(dm)
except :
	import dmRevitClasses as dm
import System, clr
from System.Collections.Generic import IList, List
bic = BuiltInCategory
dsid = ElementId(bic.OST_GenericModel)

uidoc = __revit__.ActiveUIDocument
doc = uidoc.Document

def getPipes() :
	for s in FilteredElementCollector(doc)\
		.OfCategory(BuiltInCategory.OST_PipeCurves).WhereElementIsNotElementType()\
		.ToElements() :		
			yield dm.dmElement(s)
			
			
				
pipes = list(getPipes())
wss = set()
wss1 = set()


tr = Transaction(doc, "Установка рабочего набора магистралям")
tr.Start()
for pipe in pipes :
	try :
		if pipe.diameter / dut >= 80 :
			wss.add(pipe.workset.Name)
			
			for c, e in pipe.connectedElementsWithConns :
				if c.Radius * 2 / dut  >= 80 :
					wss1.add(e.workset.Name)
					e.workset = "+АУПТ_Трубопроводы"
			pipe.workset = "+АУПТ_Трубопроводы"
	except Exception as ex :
		print(50*"-")
		print("ошибка")
		print(ex)
	
	
		

	

	
print(wss)
print(wss1)

tr.Commit()
	


	
	




