import Autodesk.Revit.UI as UI
import Autodesk.Revit.DB as DB
import re  
import math 
import clr
import System
import sys
from System.Collections.Generic import IList, List
from imp import reload
lib_path = r"D:\18_проектирование\98_PythonShell"
if not lib_path in sys.path :
    sys.path.append(lib_path)

dut = 0.0032808398950131233
#dut = DB.UnitUtils.ConvertToInternalUnits(1, DB.DisplayUnitType.DUT_MILLIMETERS)

try :
	reload(dm)
	print("перезагрузили")
except Exception as ex:
	print("ошибка при загрузке")
	print(ex)
	import dmSetGrid as dm


import random	
import re
av = dm.dmView(uidoc.ActiveView)

bl = av[2]
av.resetGridBubbles()
av.showHideGridBubbles()
av.alignGridEnds(25*dut)
av.alignGridBubbles()
av.createDimensions()

views = {v.Name : dm.dmView(v) for v in FilteredElementCollector(doc).OfClass(ViewPlan) if
			v.GetTypeId().IntegerValue == 2288361 and v.Name > "04"}
			
for v in sorted(views) :
	print(v)

if True :
	#app = dm.dmApp4Views()
	
	for v in views.values() :
		print(v.view.Name)
		v.showHideGridBubbles()		
		v.alignGridEnds(25*dut)
		v.resetGridBubbles()
		v.alignGridBubbles()
		v.createDimensions()
	

