# Для проекта Аэропорт. Установка параметра DM_Раздел_спецификации
# в зависимости от того на каком виде видимый
import Autodesk.Revit.UI as UI
import sys
from collections import deque
import math
from imp import reload
libpath = r"D:\18_проектирование\pyRevitExtension\DMuzer.extension\lib"
if libpath not in sys.path :
	sys.path.append(libpath)
dut = 0.0032808398950131233	
try :
	reload(dm)
except :
	import dmRevitClasses as dm
import System, clr
from System.Collections.Generic import IList, List
bic = BuiltInCategory
dsid = ElementId(bic.OST_GenericModel)

FltCategories = System.Array[bic]([ bic.OST_PipeCurves, 
		bic.OST_PipeFitting, 
		bic.OST_PipeAccessory, 
		bic.OST_Sprinklers, 
		bic.OST_MechanicalEquipment
		])
emcf = ElementMulticategoryFilter(FltCategories)

views = FilteredElementCollector(doc).OfClass(View3D).ToElements() 
with dm.trans() :
	for view in views :
		if not view.Name.StartsWith("Раздел_") : continue
		
		partName = view.Name[7:]
		print(partName)
		
		elements = [dm.dmElement(e) for e in FilteredElementCollector(doc, view.Id).WherePasses(emcf).ToElements()]
		
		for element in elements :
			element.Set("DM_Раздел_спецификации", partName)
			
			# Устанавливаем на зависимых элементах 
			for elementId in element.e.GetDependentElements(None) :
				subElement = dm.dmElement(elementId)
				subElement.Set("DM_Раздел_спецификации", partName)
				
	