"""
***************************************************************
*** СОЗДАНИЕ ВЕТКИ СПРИНКЛЕРОВ БЕЗ ОГРАНИЧЕНИЯ Н
*** 
***************************************************************
* Убрано ограничение на то чтобы спринклер проецировался на 
* трубу, при необходимости добавляется дополнительный участок трубы
* чтобы подойти к точке подключения
***************************************************************
"""
dut = 0.0032808398950131233

view_name = 'DM_ОТМЕТКИ'
margin_rel = False
margin = 200 * dut



from Autodesk.Revit import *
from Autodesk.Revit.DB import *
from contextlib import contextmanager
import math, sys
import clr
import System

clr.AddReferenceToFileAndPath(r"C:\Users\Дмитрий\NetTopologySuite.2.4.0\lib\netstandard2.0\NetTopologySuite.dll")
clr.AddReferenceToFileAndPath(r"C:\Program Files\Autodesk\Revit 2021\RevitAPIIFC.dll")
import NetTopologySuite as nts
import NetTopologySuite.Geometries as nts_geom
from Autodesk.Revit.DB import IFC as ifc

lib_path = r"D:\18_проектирование\98_PythonShell"
if not lib_path in sys.path :
	sys.path.append(lib_path)
	
import dm_connect_2 as dm
import dm_nearest_geometry as dm1
import dm_connect_3 as dm3

reload(dm)	
reload(dm1)
reload(dm3)

pi2 = math.pi * 2

dut = 0.0032808398950131233
	
bic = BuiltInCategory
bip = DB.Structure.StructuralType
nonstr = bip.NonStructural
OT = UI.Selection.ObjectType

uidoc = __revit__.ActiveUIDocument
doc = uidoc.Document

i = 0

while True :
	i += 1
	if i > 50 : break
	
	try :

		sprinklers_refs = uidoc.Selection.PickObjects(OT.Element)
		sprinklers = [e_ref.ElementId.IntegerValue for e_ref in sprinklers_refs]
		
		pipe_ref = uidoc.Selection.PickObject(OT.Element)
		pipe = pipe_ref.ElementId.IntegerValue
	except :
		break
		
	calc = dm3.dmConnectUtils(
			pipe_id = pipe,
			sprs_ids = sprinklers,
			end_cap=True,
			
	)
	
	calc.Calculate()
	calc.CreatePipesFromRoute()
	calc.ConnectSprinklers()




