#  coding: utf-8 


from Autodesk.Revit import *
from Autodesk.Revit.DB import *
from contextlib import contextmanager
import math, sys
import clr
import System

clr.AddReferenceToFileAndPath(r"C:\Users\Дмитрий\NetTopologySuite.2.4.0\lib\netstandard2.0\NetTopologySuite.dll")
import NetTopologySuite as nts
import NetTopologySuite.Geometries as nts_geom





lib_path = r"D:\18_проектирование\98_PythonShell"
if not lib_path in sys.path :
	sys.path.append(lib_path)


pi2 = math.pi * 2

dut = 0.0032808398950131233

	
bic = BuiltInCategory
bip = DB.Structure.StructuralType
nonstr = bip.NonStructural

uidoc = __revit__.ActiveUIDocument
doc = uidoc.Document

sel0 = uidoc.Selection.GetElementIds()

if len(sel0) > 0 :
	sel1 = sel0
print(sel0)

for e in sel1 :
	print(type(doc.GetElement(e)))
	

import dm_connect_2 as dm

import dm_nearest_geometry as dm1

reload(dm)	
reload(dm1)

av = uidoc.ActiveView

app =dm.dmApp(doc)

vis_flt = VisibleInViewFilter(doc, av.Id)
cats = System.Array[bic]([
	bic.OST_PipeCurves, bic.OST_PipeFitting, 
	bic.OST_Sprinklers, bic.OST_PipeAccessory, 
	bic.OST_MechanicalEquipment
])
mcat_flt = ElementMulticategoryFilter(cats)

fc = FilteredElementCollector(doc).WherePasses(mcat_flt).WherePasses(vis_flt).ToElements()

fc_l = list(fc)
print(len(fc_l))

ws = app.worksets['СПР 4 секц']

with dm.trans(doc) as trans :

	for e in fc :
		dm.set_workset(e, ws, trans)



