st_cmt = """
***************************************************************
*** Работа Создание разреза вдоль трубы
*** D:\18_проектирование\98_PythonShell\СОЮЗ\03_Создать разрез по трубе.txt
***************************************************************
*  
***************************************************************
"""
print("Начинаем работу. \n {}".format(st_cmt))
from Autodesk.Revit import *
import math
dut = 0.0032808398950131233
ot = UI.Selection.ObjectType
pipe_id = uidoc.Selection.PickObject(ot.Element)
pipe = doc.GetElement(pipe_id)
lc = pipe.Location.Curve
p1 = lc.GetEndPoint(0)
p2 = lc.GetEndPoint(1)
d = lc.Direction
d = XYZ(d.X, d.Y, 0).Normalize()

viewSortParamValue = uidoc.ActiveView.LookupParameter("Вид_Сортировка").AsString()

level = pipe.ReferenceLevel

elevation = level.Elevation

bottom = elevation - 1000 * dut
top = max(p1.Z, p2.Z) + 1000 * dut 

w = (p2 - p1).GetLength() * 1.3 + 5000 * dut
h = top - bottom

rot_trans = Transform.CreateRotation(XYZ.BasisZ, -math.pi / 2)
dn = rot_trans.OfVector(d)

pntMin = XYZ(-w / 2, -h / 2, -1)
pntMax = XYZ(w  / 2 ,  h / 2, 1)

origin = XYZ((p2.X+p1.X)*0.5, (p2.Y+p1.Y)*0.5, (top+bottom) * 0.5)

viewTransform = Transform.Identity
viewTransform.BasisZ = dn.Normalize()
viewTransform.BasisX = d
viewTransform.BasisY = XYZ.BasisZ
viewTransform.Origin = origin


bb = BoundingBoxXYZ()
bb.Min = pntMin
bb.Max = pntMax 
bb.Enabled = True 

bb.Transform = viewTransform

vt_id = ElementId(4517251)
tr = Transaction(doc)
tr.Start("add new pipe section")
new_view = ViewSection.CreateSection(doc, vt_id, bb)
new_view.LookupParameter("Вид_Сортировка").Set(viewSortParamValue)
new_view.Name = f"Разрез по трубе {pipe.Id}"
tr.Commit()
uidoc.ActiveView = new_view